SELECT * FROM EquipmentCategory;
SELECT * FROM EquipmentType;
SELECT * FROM CategoryType;
SELECT * FROM StorageLocation;
SELECT * FROM EquipmentAsset;
SELECT * FROM EquipmentItem;
SELECT * FROM EquipmentStock;
SELECT * FROM Recipient;
SELECT * FROM EquipmentAssignment;
